channel_urls = {
    'decred': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'ethereumclassic': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'komodo': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'gamecredits-mobilego': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'blocknet': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'ripple': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'waves': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'viacoin': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'vertcoin': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'stellar': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'zcoin': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'radium': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'blackcoin': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'librarycredits': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'zcash': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'litecoin': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'stratis': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'florincoin': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'siacoin': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'dash': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'edgeless': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'status': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'databits': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'expanse': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'ark': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--',
    'exchanges': 'https://hooks.slack.com/services/--redacted--/--redacted--/--redacted--'
}
